name: Make sure yaml and script are OK

on: [pull_request]

jobs:
  dryrun:
    name: Make sure yaml and script are OK
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: '3.6'

      - name: Install deps
        run: |
         python -m pip install --upgrade pip black
         pip install -r requirements.txt

      - name: Linting
        run: |
          black --check .

      - name: Dry run
        run: |
          ./sync_known_issues.py --dry-run -c *.yaml
