name: Update Known Issues

on: [push]

jobs:
  update:
    name: Update Known Issues
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: '3.6'

      - name: Install deps
        run: |
         python -m pip install --upgrade pip black
         pip install -r requirements.txt

      - name: Linting
        run: |
          black --check .

      - name: Sync known-issues
        env:
          QA_REPORTS_KNOWN_ISSUE_TOKEN: ${{ secrets.QA_REPORTS_KNOWN_ISSUE_TOKEN }}
        run: |
          ./sync_known_issues.py -c *.yaml $@
